# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-11 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsportal', '0005_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='overall_rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
