# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-12 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsportal', '0006_review_overall_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.FloatField(blank=True, db_index=True),
        ),
    ]
